### PR TITLE
Draft cerebellum usecase

### PR DESCRIPTION
**Pull request by Helveg**
Proposed addition of cerebellum usecase. The usecase should be linked to a `lab.ebrains.eu` execution context of this drive folder https://drive.ebrains.eu/d/3a16c9d4eaa540a6a8fa/

### CODE REVIEW

**Comment by stefanoantonel** [comment]
In this current implementation of the wizard we only support git repos and not ebrains drives.
If you have the notebook in some git we can integrate it.
For example we have this repo https://github.com/ebrains-cls-interactive/Synaptic_Events_Fitting_User_Data that pulls all the data in that repo and redirect to the specified notebook.

**Comment by stefanoantonel** [comment]
@Helveg Do you have repo? Otherwise we can create one in the CLS as we did in the past
https://github.com/orgs/ebrains-cls-interactive/repositories?q=cerebellum&type=all&language=&sort=

**Comment by Helveg** [comment]
You can make a repo from the files; when is support for Drive folders expected?

**Comment by stefanoantonel** [comment]
So I would need to have some **description** so the use case looks better. You can put it here and I can add it to the file.

So far what the end users will see is
Screenshot 2022-03-10 at 08 57 35

**Comment by Helveg** [comment]
Ok, I adressed that with [18da500](https://github.com/ebrains-cls-interactive/usecases-info/pull/13/commits/18da5003fdb29fbd434cb97295db27ff34d93519)

**Comment by stefanoantonel** [comment]
Use case added in development https://bluebrain.github.io/bsp-usecase-wizard/dev/index.html#/small_circuit_insilico_experiments

**Comment by Helveg** [comment]
I tried it out, and I A) don't understand the implications of choosing a "destination collab" B) always get a git error when it tries to synchronize:

```
$ git clone --branch main -- https://github.com/ebrains-cls-interactive/Cerebellum_multicompartment_simulation /opt/app-root/src/shared/Multicompartmental simulation of the cerebellar scaffold model/CLS-INTERACTIVE-UC/Cerebellum_multicompartment_simulation
fatal: could not create leading directories of '/opt/app-root/src/shared/Multicompartmental simulation of the cerebellar scaffold model/CLS-INTERACTIVE-UC/Cerebellum_multicompartment_simulation': No such file or directory
Traceback (most recent call last):
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/dist-packages/nbgitpuller/handlers.py", line 88, in pull
    raise e
File "/usr/local/lib/python3.8/dist-packages/nbgitpuller/handlers.py", line 82, in pull
    for line in gp.pull():
File "/usr/local/lib/python3.8/dist-packages/nbgitpuller/pull.py", line 144, in pull
    yield from self.initialize_repo()
File "/usr/local/lib/python3.8/dist-packages/nbgitpuller/pull.py", line 158, in initialize_repo
    yield from execute_cmd(clone_args)
File "/usr/local/lib/python3.8/dist-packages/nbgitpuller/pull.py", line 45, in execute_cmd
    raise subprocess.CalledProcessError(ret, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '--branch', 'main', '--', 'https://github.com/ebrains-cls-interactive/Cerebellum_multicompartment_simulation', '/opt/app-root/src/shared/Multicompartmental simulation of the cerebellar scaffold model/CLS-INTERACTIVE-UC/Cerebellum_multicompartment_simulation']' returned non-zero exit status 128.
```

(Is it going to overwrite files in those collabs?? If so: a big fat warning should be added before we recklessly delete user data; and an option should be given to create a _new_ collab instead)

**Comment by stefanoantonel** [comment]
Hi Robin,
A) we need to choose the destination collab so the notebook + files are added to the user's collab.
B) this occurs because the drive is not yet mounted into the jupyterlab. Ebrains is aware of this issue. But it should work after one or two minutes when the drive is mounted. Then you should not have this issue unless you stop the server.
C) these won't erase user's data

**Comment by Helveg** [comment]
C) Well it will in case of existing file conflicts right?

So if I understand correctly, the git repository is imported into the collab right? Wouldn't it be more user friendly to give the user the option to import it into a new, blank, empty collab too? I don't want to import this into any of my existing collabs :)

**Comment by stefanoantonel** [comment]
C) we are using https://jupyterhub.github.io/nbgitpuller/topic/automatic-merging.html

Unfortunately, creation of Collabs is not supported by the wizard yet because there was an issue in the API when creating it programatically.
You can create it and the use the wizard.

**Comment by Helveg** [comment]
Well that assumes that the repo being synced has the same content as the repo being imported; but as I (and other users) might not know that things are going to be imported, we could be selecting _any_ kind of repo, which might have accidentally overlapping files. I think it would be a lot safer in this sense that the default is to suggest creating a new collab, but I understand the open issue.

I will write this up as a separate issue that can be solved when upstream fixes the API issue :)

**Pull request merged**
