### PR TITLE
Use new Ebrains urls with "apps.ebrains.eu"

### PR DESCRIPTION
**Pull request by stefanoantonel**

### CODE REVIEW

**Comment by stefanoantonel** [comment]
@lbologna can you test when you have time?

https://bluebrain.github.io/bsp-usecase-wizard/dev/index.html

I'm pointing the use cases to the new `apps.ebrains.eu` url

**Comment by lbologna** [comment]
> @lbologna can you test when you have time?
> 
> https://bluebrain.github.io/bsp-usecase-wizard/dev/index.html
> 
> I'm pointing the use cases to the new `apps.ebrains.eu` url

Hi Stefano,
the bluenaas seems to work fine, thank you.
Is the wss endpoint still the same: wss://blue-naas-svc-bsp-epfl.apps.hbp.eu/ws ?

I also tried the other web app but it seems there's a security issue here:
https://bluenaas-small-area.apps.tc.humanbrainproject.eu/circuits/mouse-sscx
https://bluenaas-small-area.apps.tc.humanbrainproject.eu/circuits/rat-ca1

and Not Found here:
https://bluenaas-brain-area.apps.tc.humanbrainproject.eu/index.html#/circuits/hippo_mooc_sa_microcircuit
https://bluenaas-brain-area.apps.tc.humanbrainproject.eu/index.html#/circuits/hippo_hbp_sa_full_ca1

**Comment by stefanoantonel** [comment]
There might be an error with the cache.

The new url that you should see is `https://bluenaas-single-cell.apps.ebrains.eu/` also I've brought back the models selection before opening bluenaas. (In the [dev environment](https://bluebrain.github.io/bsp-usecase-wizard/dev/index.html)) if you can give it a new try in some incognito mode

**Review by lbologna — APPROVED** [review]
Working fine. Thank you!

**Pull request merged**
